version: "3.7"
services:
  app:
    build: .
    ports:
      - "8090:8080"
    networks:
      - s-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: kamal
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: kamal
    ports:
      - "5433:5432"
    networks:
      - s-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
networks:
  s-network:
    driver: bridge
volumes:
  postgres-data:


